### ISSUE TITLE
Unable to build with DMD 2.068.2

### ISSUE THREAD

**Issue by whitebyte** [CyberShadow/DBuildStat#3]
Hi, I'm trying to build DBuildStat with the latest DMD on openSUSE Tumbleweed x64. Unfortunatenely I recieve a whole bunch of cryptic error messages (https://gist.github.com/whitebyte/246fb5a949186aa1953a). I don't have guts to handle it on my own, could you point me to the right direction?

**Comment by MartinNowak** [comment]
Looks like you're not compiling the ae library. Have you checked out and updated the git submodule?

**Comment by whitebyte** [comment]
Tried to do this, still no luck.

**Comment by CyberShadow** [comment]
Pushed some changes that were lying on my hard drive plus some build fixes. Builds fine for me now with 2.067 and 2.068.

**Comment by whitebyte** [comment]
It works, thanks.
