### ISSUE TITLE
Dub integration?

### ISSUE THREAD

**Issue by whitebyte** [CyberShadow/DBuildStat#4]
Is there any way to use dbuildstat for dub generated projects without explicitly providing all filenames for linking?

**Comment by CyberShadow** [comment]
Simply pass your program's entry point file with all necessary `-I` import paths.

**Comment by whitebyte** [comment]
That's exactly what I'm trying to avoid.

**Comment by CyberShadow** [comment]
You can use `dub -v` to get the import paths from Dub.

**Comment by whitebyte** [comment]
Ok, will try, thanks
